multierror: switch to golang's multi-error wrapping
Stop building our own multi-error handling package and instead use
go's standard library error package for wrapping multiple errors.
This requires golang 1.20 as a prerequisite.

Signed-off-by: Muyassarov, Feruzjon <feruzjon.muyassarov@intel.com>